# Generated by Django 4.2.4 on 2024-12-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
