# Generated by Django 4.2.4 on 2024-12-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0010_remove_order_cart_items_order_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_item',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
